# Generated by Django 5.1.1 on 2024-10-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_details',
            name='name',
        ),
        migrations.AddField(
            model_name='students_details',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students_details',
            name='course',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students_details',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students_details',
            name='phnum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students_details',
            name='place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='students_details',
            name='Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
