# Generated by Django 5.1.1 on 2024-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_students_details_idnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
