# Generated by Django 5.1.1 on 2024-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_fees_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paidfees', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paid_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('Totalfees', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pending_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('paidfees', models.IntegerField(null=True)),
                ('pendingfees', models.IntegerField(null=True)),
            ],
        ),
    ]
