# Generated by Django 5.1.1 on 2024-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0005_fees_report_paid_fees_pending_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_details',
            name='phnum',
            field=models.BigIntegerField(blank=True),
        ),
    ]
