# Generated by Django 5.1.1 on 2024-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0006_alter_students_details_phnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_details',
            name='idnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students_details',
            name='phnum',
            field=models.BigIntegerField(),
        ),
    ]
