# Generated by Django 5.1.1 on 2024-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0007_alter_students_details_idnum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidfees', models.IntegerField(blank=True, null=True)),
                ('paiddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
