# Generated by Django 5.1.1 on 2024-11-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0008_collect_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collect_fees',
        ),
    ]
