# Generated by Django 5.1.1 on 2024-11-06 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0009_delete_collect_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_details',
            name='paiddate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_details',
            name='paidfees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_details',
            name='idnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_details',
            name='phnum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
