# Generated by Django 5.1.1 on 2024-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0010_students_details_paiddate_students_details_paidfees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees_payment',
        ),
        migrations.DeleteModel(
            name='fees_report',
        ),
        migrations.DeleteModel(
            name='paid_fees',
        ),
        migrations.DeleteModel(
            name='pending_fees',
        ),
    ]
