# Generated by Django 5.1.1 on 2024-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0014_students_details_coursefees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feesstrctute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('coursefees', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='students_details',
            name='coursefees',
        ),
        migrations.RemoveField(
            model_name='students_details',
            name='coursename',
        ),
    ]
