# Generated by Django 5.1.1 on 2024-11-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0015_feesstrctute_remove_students_details_coursefees_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feesstrctute',
            new_name='course',
        ),
    ]
